common/models/Ad.php
<?php

namespace common\models;

use common\components\UploadHelper;
use Yii;

/**
 * This is the model class for table "ad".
 *
 * @property integer $id
 * @property string $title
 * @property integer $type
 * @property integer $status
 * @property string $src
 *
 * @property PageHasAd[] $pageHasAds
 */
class Ad extends \yii\db\ActiveRecord {

    const TYPE_TOP_BANNER = 10;

    const STATUS_ACTIVE = 10;
    const STATUS_SUSPENDED = 20;
    const STATUS_DELETED = 30;

    public $pic;
    public $x;
    public $y;
    public $w;
    public $h;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'ad';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['title'], 'required'],
            [['type', 'status'], 'integer'],
            [['title', 'src'], 'string', 'max' => 191],
            ['type', 'default', 'value' => self::TYPE_TOP_BANNER],
            ['type', 'in', 'range' => [self::TYPE_TOP_BANNER]],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_SUSPENDED, self::STATUS_DELETED]],
            [['x', 'y', 'w', 'h'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'type' => 'Type',
            'status' => 'Status',
            'src' => 'Src',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPageHasAds() {
        return $this->hasMany(PageHasAd::className(), ['ad_id' => 'id']);
    }

    public function uploadImg() {
        if ($this->validate()) {
            if (!isset($this->w) || !isset($this->h) || !isset($this->x) || !isset($this->y)) {
                return false;
            }
            $imageInfo = getimagesize($this->pic->tempName);
            list($width, $height) = $imageInfo;

            $imageInfo = getimagesize($this->pic->tempName);
            switch ($imageInfo[2]) {
                case IMAGETYPE_JPEG :
                    $src = imagecreatefromjpeg($this->pic->tempName);
                    break;
                case IMAGETYPE_PNG :
                    $src = imagecreatefrompng($this->pic->tempName);
                    break;
                default :
                    Yii::$app->session->setFlash('error', 'Invalid image format...');
                    return false;
            }

            $rand1 = UploadHelper::randDir();
            $uniqueid = uniqid();
            $imagedir = Yii::getAlias('@uploadsPath') . DIRECTORY_SEPARATOR . $rand1;
            $directory = $imagedir . DIRECTORY_SEPARATOR . "image_" . $uniqueid . '.jpg';

            $directorydb = '/' . $rand1 . "/image_" . $uniqueid . '.jpg';

            if (!file_exists($imagedir)) {
                mkdir($imagedir, 0777, true);
            }

            //Cropped Image
            if ($this->w > 1080) {
                $destW = 1080;
            } else {
                $destW = $this->w;
            }
            $destH = $destW / 4;

            $croppedImage = imagecreatetruecolor($destW, $destH);
            imagecopyresampled($croppedImage, $src, 0, 0, $this->x, $this->y, $destW, $destH, $this->w, $this->h);

            imagejpeg($croppedImage, $directory);
            imagedestroy($croppedImage);

            $this->src = $directorydb;
            if ($this->save()) {
                return true;
            }
        } else {
            Yii::$app->session->setFlash('error', 'Error Saving image...');
            return false;
        }
    }

    public function coverSrc($canNull = false) {
        if (!$this->src) {
            if ($canNull) {
                return null;
            }
            return 'http://placehold.it/800x200';
        }
        return Yii::getAlias("@uploads") . $this->src;
    }
}

backend/controllers/AdsController.php
<?php
namespace backend\controllers;

use common\models\Ad;
use common\models\AdSearch;
use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\UploadedFile;


class AdsController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new AdSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id = null) {
        if (!$id || !$model = Ad::findOne($id)) {
            $model = new Ad();
        }
        $POST = Yii::$app->request->post();
        if ($model->load($POST)) {
            if ($model->isNewRecord && $model->save()) {
                Yii::$app->session->setFlash('success', 'New Ad added successfully!');
                return $this->redirect(['ads/index']);
            } else if ($model->save()) {
                if (($model->pic = UploadedFile::getInstance($model, 'pic'))) {
//                    die();
                    $model->uploadImg();
                }
                Yii::$app->session->setFlash('success', 'Ad Edited successfully!');
            }
        }
        return $this->render('view', ['model' => $model]);
    }

}

backend/views/ads/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\grid\GridView;

$this->title = 'Ads';
?>
<div class="site-index">

    <?php

    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'title',
            [
                'class' => '\kartik\grid\ActionColumn',
                'template' => '{view}'
            ],
        ],
        'responsive' => true,
        'hover' => true,
        'striped' => false,
        'pjax' => true,
        'panel' => [
            'type' => 'panel panel-primary',
            'heading' => '<h3 class="panel-title"> Ads</h3>',
        ],
        'toolbar' => [
            [
                'content' =>
                    Html::a('<i class="glyphicon glyphicon-plus"></i> New', Url::toRoute("/ads/view"), [
                        'type' => 'button',
                        'title' => 'New',
                        'class' => 'btn btn-success'
                    ]),
            ]
        ],
    ]);
    ?>
</div>

backend/views/ads/view.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = $model->isNewRecord ? 'New Ad' : $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Ads', 'url' => ['/ads/index']];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><?= $this->title ?></h3>
        </div>
        <div class="panel-body">
            <?php $form = ActiveForm::begin(['id' => 'new-ad-form', 'options' => ['enctype' => 'multipart/form-data']]); ?>
            <div class="form-group">
                <div class="center squareImgMaxHeight imgHover" id="menuimg">
                    <label for="image-upload">
                        <img src="<?= $model->coverSrc() ?>"/>
                        <span class="text-content"><span>Change Picture</span></span>
                    </label>
                    <?= $form->field($model, 'x', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picX"])->label(false); ?>
                    <?= $form->field($model, 'y', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picY"])->label(false); ?>
                    <?= $form->field($model, 'w', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picW"])->label(false); ?>
                    <?= $form->field($model, 'h', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picH"])->label(false); ?>
                    <?=
                    $form->field($model, 'pic')->fileInput([
                        'class' => 'uploadimg',
                        'id' => 'image-upload',
                        'accept' => 'image/png, image/jpeg'])->label(false);
                    ?>
                </div>
                <?= $form->field($model, 'title'); ?>
                <?php //echo $form->field($model, 'status')->dropDownList($model::listStatus()) ?>
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="imageAreaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close cancelModal" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Crop Picture</h4>
                </div>
                <div class="modal-body">
                    <img class="img-responsive" id="uploadModalPreview"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default cancelModal" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="saveModal">Save changes</button>
                </div>
            </div>
        </div>
    </div>
<?php
$this->registerCssFile(Url::base() . "/lib/imgareaselect/dist/imgareaselect.css");
$this->registerJsFile(
    Url::base() . "/lib/imgareaselect/dist/jquery.imgareaselect.js", ['depends' => ['\backend\assets\AppAsset']]
);
$this->registerJsFile(
    Url::base() . "/js/ads-view.js", ['depends' => ['\backend\assets\AppAsset'], 'position' => \yii\web\View::POS_END]
);