backend/controllers/PagesController.php
<?php
namespace backend\controllers;

use common\models\Page;
use common\models\PageSearch;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;


class PagesController extends Controller {
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id = null) {
        if (!$id || !$model = Page::findOne($id)) {
            $model = new Page();
        }
        $POST = Yii::$app->request->post();
        if ($model->load($POST)) {
            if (($model->pic = UploadedFile::getInstance($model, 'pic'))) {
                if ($model->save()) {
                    if ($model->uploadImg()) {
                        Yii::$app->session->setFlash('success', 'Picture added successfully!');
                        return $this->refresh();
                    }
                }
            }
            if ($model->isNewRecord && $model->save()) {
                Yii::$app->session->setFlash('success', 'New page added successfully!');
                return $this->redirect(['pages/index']);
            } else if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Page Edited successfully!');
            }
        }
        if (isset($POST['childpages'])) {
            $pages = isset($POST['pages']) ? $POST['pages'] : [];
            $model->setPages($pages);
            $model = Page::findOne($model->id);
            Yii::$app->session->setFlash('success', 'Child pages updated successfully!');
        }
        return $this->render('page', ['model' => $model]);
    }

    public function actionRemovePagePic($id) {
        $model = Page::findOne($id);
        if ($model->removePic()) {
            Yii::$app->session->setFlash('success', 'Page image removed!');
        } else {
            Yii::$app->session->setFlash('error', 'Unable to remove page image...');
        }
        return $this->redirect(['pages/view', 'id' => $model->id]);
    }


}

backend/views/pages/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\grid\GridView;

$this->title = 'Pages';
?>
<div class="site-index">

    <?php
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'title',
            [
                'attribute' => 'type',
                'value' => function ($data) {
                    return $data->type();
                },
                'filterType' => GridView::FILTER_SELECT2,
                'filterWidgetOptions' => ['data' => [null => 'All'] + \common\models\Page::listTypes()],
            ],
            [
                'class' => '\kartik\grid\ActionColumn',
                'template' => '{view}'
            ],
        ],
        'responsive' => true,
        'hover' => true,
        'striped' => false,
        'pjax' => true,
        'panel' => [
            'type' => 'panel panel-primary',
            'heading' => '<h3 class="panel-title"> Pages</h3>',
        ],
        'toolbar' => [
            [
                'content' =>
                    Html::a('<i class="glyphicon glyphicon-plus"></i> New', Url::toRoute("/pages/view"), [
                        'type' => 'button',
                        'title' => 'New',
                        'class' => 'btn btn-success'
                    ]),
            ]
        ],
    ]);
    ?>
</div>

backend/views/pages/page.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = $model->isNewRecord ? 'New Page' : $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Pages', 'url' => ['/pages/index']];
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><?= $this->title ?></h3>
        </div>
        <div class="panel-body">
            <?php $form = ActiveForm::begin(['id' => 'new-page-form']); ?>
            <div class="form-group">
                <?php if (!$model->isNewRecord) { ?>
                    <div class="center squareImgMaxHeight imgHover" id="menuimg">
                        <label for="image-upload">
                            <img src="<?= $model->src() ?>"/>
                            <span class="text-content"><span>Change Picture</span></span>
                        </label>
                        <?= $form->field($model, 'x', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picX"])->label(false); ?>
                        <?= $form->field($model, 'y', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picY"])->label(false); ?>
                        <?= $form->field($model, 'w', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picW"])->label(false); ?>
                        <?= $form->field($model, 'h', ['options' => ['class' => 'hide']])->hiddenInput(['id' => "picH"])->label(false); ?>
                        <?=
                        $form->field($model, 'pic')->fileInput([
                            'class' => 'uploadimg',
                            'id' => 'image-upload',
                            'accept' => 'image/png, image/jpeg'])->label(false);
                        ?>
                        <?php if ($model->hasPic() && !$model->isImage()) { ?>
                            <p class="center"><?= Html::a('Remove Picture', ['pages/remove-page-pic', 'id' => $model->id]) ?></p>
                        <?php } ?>
                    </div>
                <?php } ?>
                <?= $form->field($model, 'title'); ?>
                <?php if ($model->isImage()) { ?>
                    <?= $form->field($model, 'description'); ?>
                <?php } ?>
                <?= $form->field($model, 'type')->dropDownList($model::listTypes()) ?>
                <?= $form->field($model, 'status')->dropDownList($model::listStatus()) ?>
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
<?php if (!$model->isNewRecord) { ?>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Child Pages</h3>
        </div>
        <div class="panel-body">
            <?php $form = ActiveForm::begin(['id' => 'sub-pages-form']); ?>
            <div class="form-group">
                <?= \kartik\select2\Select2::widget([
                    'name' => 'pages',
                    'value' => $model->getChildPagesList(),
                    'data' => \common\models\Page::listPages(),
                    'options' => ['multiple' => true, 'placeholder' => 'Select Pages'],
                    'maintainOrder' => true,
                ]);
                ?>
                <?= Html::input('hidden', 'childpages'); ?>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
<?php } ?>

<?php if (!$model->isNewRecord) { ?>
    <!-- Modal -->
    <div class="modal fade" id="imageAreaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close cancelModal" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Crop Picture</h4>
                </div>
                <div class="modal-body">
                    <img class="img-responsive" id="uploadModalPreview"/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default cancelModal" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="saveModal">Save changes</button>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php
if (!$model->isNewRecord) {
    $this->registerCssFile(Url::base() . "/lib/imgareaselect/dist/imgareaselect.css");
    $this->registerJsFile(
        Url::base() . "/lib/imgareaselect/dist/jquery.imgareaselect.js", ['depends' => ['\backend\assets\AppAsset']]
    );
    $this->registerJsFile(
        Url::base() . "/js/page-view.js", ['depends' => ['\backend\assets\AppAsset'], 'position' => \yii\web\View::POS_END]
    );
}